In [23]:
import numpy as np
import matplotlib.pyplot as plt
import sympy

In [20]:
A = np.array([
        [1, 2, 1],
        [2, 1, 1],
        [-1, 2, 1]
    ], dtype=np.dtype(float))

print(A,"\n")
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}")

[[ 1.  2.  1.]
 [ 2.  1.  1.]
 [-1.  2.  1.]] 

Determinant of matrix A: -2.00


In [24]:
A = np.array([
        [1, 2, 3],
        [3, 2, 1],
        [2, 2, 1]
    ], dtype=np.dtype(float))

print(A,"\n")
inds = sympy.Matrix(A).T.rref()
print(inds) #Rows that showed = Linearly independent rows. If not then linearly dependent rows

[[1. 2. 3.]
 [3. 2. 1.]
 [2. 2. 1.]] 

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


In [32]:
x=3 ; y=3; z=6
A = np.array([
        [2, 1, 5],
        [1, 2, 1],
        [x, y, z]
    ], dtype=np.dtype(float))

print(A,"\n")
inds = sympy.Matrix(A).T.rref()
print(inds) #Rows that showed = Linearly independent rows. If not then linearly dependent rows

[[2. 1. 5.]
 [1. 2. 1.]
 [3. 3. 6.]] 

(Matrix([
[1, 0, 1.0],
[0, 1, 1.0],
[0, 0,   0]]), (0, 1))


In [ ]:
A = np.array([
        [1, 2, 3],
        [3, 2, 1],
        [2, 2, 1]
    ], dtype=np.dtype(float))

print(A,"\n")
inds = sympy.Matrix(A).T.rref()
print(inds) #Rows that showed = Linearly independent 