In [23]:
import numpy as np
import matplotlib.pyplot as plt
import sympy

### Week 1

In [20]:
A = np.array([
        [1, 2, 1],
        [2, 1, 1],
        [-1, 2, 1]
    ], dtype=np.dtype(float))

print(A,"\n")
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}") #if = 0, then singular

[[ 1.  2.  1.]
 [ 2.  1.  1.]
 [-1.  2.  1.]] 

Determinant of matrix A: -2.00


In [24]:
A = np.array([
        [1, 2, 3],
        [3, 2, 1],
        [2, 2, 1]
    ], dtype=np.dtype(float))

print(A,"\n")
inds = sympy.Matrix(A).T.rref()
print(inds) #Rows that showed = Linearly independent rows. If not then linearly dependent rows

[[1. 2. 3.]
 [3. 2. 1.]
 [2. 2. 1.]] 

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


In [32]:
x=3 ; y=3; z=6
A = np.array([
        [2, 1, 5],
        [1, 2, 1],
        [x, y, z]
    ], dtype=np.dtype(float))

print(A,"\n")
inds = sympy.Matrix(A).T.rref()
print(inds) #Rows that showed = Linearly independent rows. If not then linearly dependent rows

[[2. 1. 5.]
 [1. 2. 1.]
 [3. 3. 6.]] 

(Matrix([
[1, 0, 1.0],
[0, 1, 1.0],
[0, 0,   0]]), (0, 1))


In [35]:
A = np.array([
        [1, 2, 3],
        [0, 2, 2],
        [1, 4, 5]
    ], dtype=np.dtype(float))

print(A,"\n")
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}") #if = 0, then singular

[[1. 2. 3.]
 [0. 2. 2.]
 [1. 4. 5.]] 

Determinant of matrix A: 0.00


### Week 2

In [37]:
A = np.array([
        [2, 5],
        [8, 1]
    ], dtype=np.dtype(float))

b = np.array([46, 32], dtype=np.dtype(float))

x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [3. 8.]


In [38]:
A = np.array([
        [5, 1],
        [10, 2]
    ], dtype=np.dtype(float))

b = np.array([11, 22], dtype=np.dtype(float))

x = np.linalg.solve(A, b)

print(f"Solution: {x}")

LinAlgError: Singular matrix

In [41]:
A = np.array([
        [1, 1],
        [-6, 2]
    ], dtype=np.dtype(float))

b = np.array([4, 16], dtype=np.dtype(float))

x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [-1.  5.]


In [43]:
A = np.array([
        [4, -3],
        [7, -8]
    ], dtype=np.dtype(float))

print(A,"\n")
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}") #if = 0, then singular

[[ 4. -3.]
 [ 7. -8.]] 

Determinant of matrix A: -11.00


In [45]:
A = np.array([
        [-3, 8, 1],
        [2, 2, -1],
        [-5, 6, 2]
    ], dtype=np.dtype(float))

print(A,"\n")
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}") #if = 0, then singular

[[-3.  8.  1.]
 [ 2.  2. -1.]
 [-5.  6.  2.]] 

Determinant of matrix A: -0.00


In [46]:
"""
A = np.array([
        [a, b, c],
        [d, e, f],
        [2*a-d, 2*b-e, 2*c-f]
    ], dtype=np.dtype(float))

Dependent
"""

'\nA = np.array([\n        [a, b, c],\n        [d, e, f],\n        [2*a-d, 2*b-e, 2*c-f]\n    ], dtype=np.dtype(float))\nDependent\n'

In [53]:
x=1; y=x; z=3
A = np.array([
        [x, x],
        [y, z]
    ], dtype=np.dtype(float))

print(A,"\n")
d = np.linalg.det(A)
print(f"Determinant of matrix A: {d:.2f}") #if = 0, then singular

[[1. 1.]
 [1. 3.]] 

Determinant of matrix A: 2.00


In [55]:
A = np.array([
        [5, 1],
        [-1, 3]
    ], dtype=np.dtype(float))

print(A,"\n")
print("The Rank of a Matrix: ", np.linalg.matrix_rank(A))

[[ 5.  1.]
 [-1.  3.]] 

The Rank of a Matrix:  2


In [56]:
A = np.array([
        [2, -1],
        [-6, 3]
    ], dtype=np.dtype(float))

print(A,"\n")
print("The Rank of a Matrix: ", np.linalg.matrix_rank(A))

[[ 2. -1.]
 [-6.  3.]] 

The Rank of a Matrix:  1


In [77]:
A = np.array([
        [1, 3],
        [3, 12]
    ], dtype=np.dtype(float))

b = np.array([15, 3], dtype=np.dtype(float))

x = np.linalg.solve(A, b)

print(f"Solution: {x}")
print(f"Solution: {(x * np.array([1, 3]))}")
print(f"Solution: {sum(x * np.array([1, 3]))}")
print(f"Solution: {sum(x * np.array([4, 15]))}")

Solution: [ 57. -14.]
Solution: [ 57. -42.]
Solution: 15.0
Solution: 18.0


In [62]:
A = np.array([
        [2, 1],
        [4, 2]
    ], dtype=np.dtype(float))

b = np.array([5, 10], dtype=np.dtype(float))

x = np.linalg.solve(A, b) #if error : LinAlgError: Singular matrix. Then The system has infinitely many solutions.

LinAlgError: Singular matrix

In [65]:
A = np.array([
        [1, 2, 3],
        [2, 6, 12],
        [4, -8, 4]
    ], dtype=np.dtype(float))

b = np.array([10, 4, 8], dtype=np.dtype(float))

x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [14.  4. -4.]


In [66]:
A = np.array([
        [3, 1],
        [6, 2]
    ], dtype=np.dtype(float))

print(A,"\n")
print("The Rank of a Matrix: ", np.linalg.matrix_rank(A))

[[3. 1.]
 [6. 2.]] 

The Rank of a Matrix:  1


In [67]:
import numpy as np
# Function to check if matrix is in REF
 
def is_row_echelon_form(matrix):
    if not matrix.any():
        return False
 
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    prev_leading_col = -1
 
    for row in range(rows):
        leading_col_found = False
        for col in range(cols):
            if matrix[row, col] != 0:
                if col <= prev_leading_col:
                    return False
                prev_leading_col = col
                leading_col_found = True
                break
        if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
            return False
    return True
 
def find_nonzero_row(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0:
            return row
    return None
 
# Swapping rows so that we can have our non zero row on the top of the matrix
def swap_rows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]
 
def make_pivot_one(matrix, pivot_row, col):
    pivot_element = matrix[pivot_row, col]
    matrix[pivot_row] //= pivot_element
    # print(pivot_element)
 
def eliminate_below(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    pivot_element = matrix[pivot_row, col]
    for row in range(pivot_row + 1, nrows):
        factor = matrix[row, col]
        matrix[row] -= factor * matrix[pivot_row]
 
# Implementing above functions
def row_echelon_form(matrix):
    nrows = matrix.shape[0]
    ncols = matrix.shape[1]
    pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
    for col in range(ncols):
        nonzero_row = find_nonzero_row(matrix, pivot_row, col)
        if nonzero_row is not None:
            swap_rows(matrix, pivot_row, nonzero_row)
            make_pivot_one(matrix, pivot_row, col)
            eliminate_below(matrix, pivot_row, col)
            pivot_row += 1
    return matrix

In [69]:
A = np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 0]
    ], dtype=np.dtype(float))
print("Matrix Before Converting:")
print(A)
print()
result = row_echelon_form(A)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
    print("In REF")
else:
    print("Not in REF--------------->")

Matrix Before Converting:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]

After Converting to Row Echelon Form:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
In REF


In [70]:
A = np.array([
        [1, 1, 1],
        [0, 1, 1],
        [0, 0, 1]
    ], dtype=np.dtype(float))
print("Matrix Before Converting:")
print(A)
print()
result = row_echelon_form(A)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
    print("In REF")
else:
    print("Not in REF--------------->")

Matrix Before Converting:
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]

After Converting to Row Echelon Form:
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
In REF


In [72]:
A = np.array([
        [1, 0, 0],
        [1, 0, 1],
        [0, 0, 1]
    ], dtype=np.dtype(float))
print("Matrix Before Converting:")
print(A)
print()
result = row_echelon_form(A)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
    print("In REF")
else:
    print("Not in REF--------------->")

Matrix Before Converting:
[[1. 0. 0.]
 [1. 0. 1.]
 [0. 0. 1.]]

After Converting to Row Echelon Form:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
In REF


In [73]:
A = np.array([
        [0, 0, 1],
        [0, 1, 2],
        [0, 0, 0]
    ], dtype=np.dtype(float))
print("Matrix Before Converting:")
print(A)
print()
result = row_echelon_form(A)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
    print("In REF")
else:
    print("Not in REF--------------->")

Matrix Before Converting:
[[0. 0. 1.]
 [0. 1. 2.]
 [0. 0. 0.]]

After Converting to Row Echelon Form:
[[0. 1. 2.]
 [0. 0. 1.]
 [0. 0. 0.]]
In REF


In [75]:
A = np.array([
        [1, 3, 2],
        [2, 1, 5],
        [3, 4, 4]
    ], dtype=np.dtype(float))
print("Matrix Before Converting:")
print(A)
print()
result = row_echelon_form(A)
print("After Converting to Row Echelon Form:")
print(result)
if is_row_echelon_form(result):
    print("In REF")
else:
    print("Not in REF--------------->")

Matrix Before Converting:
[[1. 3. 2.]
 [2. 1. 5.]
 [3. 4. 4.]]

After Converting to Row Echelon Form:
[[ 1.  3.  2.]
 [-0.  1. -1.]
 [-0. -0.  1.]]
In REF


In [78]:
A = np.array([
        [2, 1, 5],
        [1, 3, 1],
        [3, 4, 6]
    ], dtype=np.dtype(float))

print(A,"\n")
print("The Rank of a Matrix: ", np.linalg.matrix_rank(A))

[[2. 1. 5.]
 [1. 3. 1.]
 [3. 4. 6.]] 

The Rank of a Matrix:  2


### Week 3

In [82]:
v1 = np.array([ [1,3] ], dtype=np.dtype(float))
v2 = np.array([ [6,2] ], dtype=np.dtype(float))
print(v1 + v2)
print(v1 - v2)

[[7. 5.]]
[[-5.  1.]]


In [86]:
a = np.array([ [-1, 5, 2] ], dtype=np.dtype(float))
b = np.array([ [-3, 6, -4] ], dtype=np.dtype(float))
print(np.dot(a, b.T))

[[25.]]


In [88]:
a = np.array([0, 0, 0])  
b = np.array([1, 9, 8])  
print(np.dot(a, a.T))
print(np.dot(a, b.T))

0
0


In [90]:
a = np.array([
        [3, 1, 4],
        [2, -1, 2]
    ], dtype=np.dtype(float))

b = np.array([
        [3, 0, 1, -2],
        [1, 5, 2, 0],
        [-2, 1, 4, 0]
    ], dtype=np.dtype(float))

print(np.dot(a, b))

[[ 2.  9. 21. -6.]
 [ 1. -3.  8. -4.]]


In [93]:
from sympy import Rational
A = np.array([
        [5, 2],
        [1, 2]
    ], dtype=np.dtype(float))

A_inv = np.linalg.inv(A)

A_inv_frac = np.array([[Rational(x).limit_denominator() for x in row] for row in A_inv])

print(A_inv_frac)

[[1/4 -1/4]
 [-1/8 5/8]]


In [94]:
A = np.array([
        [1, 1],
        [2, 2]
    ], dtype=np.dtype(float))

A_inv = np.linalg.inv(A)

A_inv_frac = np.array([[Rational(x).limit_denominator() for x in row] for row in A_inv])

print(A_inv_frac)

LinAlgError: Singular matrix